# Final linear Algebra Project

Zhihong Zhang

In [0]:
#set up required library
from sympy import abc
import numpy as np
import math
#for deep copy
import copy
import scipy.linalg as la

## Part 1: Solve a system of equations

Firstly, I set up with a system of equation.
$$\begin{array}{lrcrcrcr}
        E_{1j}: & 2x_{1} & + & 6x_{2} & + & 2x_{3} & = & 2 \\
        E_{2j}: & 5x_{1} & + & 9x_{2} & + & 0x_{3} & = & -1 \\
        E_{3j}: & x_{1} & + & 4x_{2} & + & 2x_{3} & = & 3
\end{array}$$



Based on the system, we then can write two matrix. 

> Using the matrix from the system above, we have:

> $$M = \left[ \begin{array}{rrr}  2 &  6 & 2  \\
                      5 & 9 & 0  \\
                     1 &  4 & 2  \end{array}  \right]$$
                                  
  $$b = \left[ \begin{array}{rrr}  2  \\
                     -1  \\
                 3  \end{array}  \right]$$

In this problem I use built in function, basically use inverse function to get the answer. $X= M^{-1}*b$ In general, it is not a good idea if M is large enough and it is computationally expensive. But it is good enough in this simple case.

In [283]:
M = np.array([[2,6,2],[5,9,0],[1,4,2]])
b=np.array([[2],[-1],[3]])
X=np.dot(np.linalg.inv(M),b)
print("answer is: \n ",X)

answer is: 
  [[ 7.]
 [-4.]
 [ 6.]]


As the result shows,   $$X = \left[ \begin{array}{rrr}  7  \\
                     -4  \\
                 6  \end{array}  \right]$$

I checked answer with substitube values into the equation, all of three equations work. 

## Part 2: Write a function and solve using elimination

To make problem easier, for one test case, we continue to use the matrice from part one.
 $$M = \left[ \begin{array}{rrr}  2 &  6 & 2  \\
                      5 & 9 & 0  \\
                     1 &  4 & 2  \end{array}  \right]$$
                                  
  $$b = \left[ \begin{array}{rrr}  2  \\
                     -1  \\
                 3  \end{array}  \right]$$

In [284]:

#make aumented matrix
part2_ex1=np.column_stack((M, b))
part2_ex1=np.asfarray(part2_ex1,float)
part2_ex1

array([[ 2.,  6.,  2.,  2.],
       [ 5.,  9.,  0., -1.],
       [ 1.,  4.,  2.,  3.]])

In [0]:
def mygauss(a, b):
    a = copy.deepcopy(a)
    b = copy.deepcopy(b)
    n = len(a)
    p = len(b[0])
    det = 1
    for i in range(n - 1):
        k = i
        for j in range(i + 1, n):
            if abs(a[j][i]) > abs(a[k][i]):
                k = j
        if k != i:
            a[i], a[k] = a[k], a[i]
            b[i], b[k] = b[k], b[i]
            det = -det
 
        for j in range(i + 1, n):
            t = a[j][i]/a[i][i]
            for k in range(i + 1, n):
                a[j][k] -= t*a[i][k]
            for k in range(p):
                b[j][k] -= t*b[i][k]
 
    for i in range(n - 1, -1, -1):
        for j in range(i + 1, n):
            t = a[i][j]
            for k in range(p):
                b[i][k] -= t*b[j][k]
        t = 1/a[i][i]
        det *= a[i][i]
        for j in range(p):
            b[i][j] *= t
    return det, b

In [0]:
mygauss(M,b)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:29: RuntimeWarning: divide by zero encountered in long_scalars
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in multiply


ValueError: ignored

Since function does not work properly, I tried to construct upper triangle firstly.

### Way one : Construct upper triangle

In [0]:
def gauss(A):
  
    m = len(A)
    n = m + 1
    
    for k in range(m):
        pivots = [abs(A[i][k]) for i in range(k, m)]
        i_max = pivots.index(max(pivots)) + k
        
        # Check for singular matrix
        assert A[i_max][k] != 0, "Matrix is singular!"
        
        # Swap rows
        A[k], A[i_max] = A[i_max], A[k]

        
        for i in range(k + 1, m):
            f = A[i][k] / A[k][k]
            for j in range(k + 1, n):
                A[i][j] -= A[k][j] * f

            # Fill lower triangular matrix with zeros:
            A[i][k] = 0
    
    # Solve equation Ax=b for an upper triangular matrix A         
    x = []
    for i in range(m - 1, -1, -1):
        x.insert(0, A[i][m] / A[i][i])
        for k in range(i - 1, -1, -1):
            A[k][m] -= A[k][i] * x[0]
    return x

In [0]:
def my_eli(m):

	dim = m.shape[0]
	E = np.mat(np.eye(dim))
	L = np.mat(np.eye(dim))
	U = m.copy()
	for i in range(dim):
  
		L[i+1:,i] = U[i+1:,i] / U[i,i]
		E[i+1:,:] = E[i+1:,:] - L[i+1:,i]*E[i,:]
		U[i+1:,:] = U[i+1:,:] - L[i+1:,i]*U[i,:]
 
 
	print("L= \n",L)
	print("U= \n",U)
	print("Then there is:")
	print("E= \n",E)
  

In [290]:
#convert format into matrix
#array does not work properly
my_eli(np.mat(M))

L= 
 [[ 1.          0.          0.        ]
 [ 2.5         1.          0.        ]
 [ 0.5        -0.16666667  1.        ]]
U= 
 [[ 2  6  2]
 [ 0 -6 -5]
 [ 0  0  0]]
Then there is:
E= 
 [[ 1.          0.          0.        ]
 [-2.5         1.          0.        ]
 [-0.91666667  0.16666667  1.        ]]


After we have upper triangle, wethen can do back substitution.

In [0]:
#incomplete function
def back_substitution(A: np.ndarray, b: np.ndarray) -> np.ndarray:
    """
    Returns the string and use back_substitution
    """
    n = b.size
    #construct array with all zeros
    x = np.zeros_like(b)


    x[n-1] = b[n-1]/A[n-1, n-1]
    C = np.zeros((n,n))
    for i in range(n-2, -1, -1):
        bb = 0
        for j in range (i+1, n):
            bb += A[i, j]*x[j]

        C[i, i] = b[i] - bb
        x[i] = C[i, i]/A[i, i]

    return x

In [0]:
back_substitution(E)

NameError: ignored

### Way two :  apply the Gauss Jordan elimination procedures


Now we can start the Gauss Jordan process, firstly we make aumented matrix.

In [292]:
#test matrix
N = np.array([[2,3,3],[3,-1,2],[1,4,2]])
b_part2=np.array([[1],[-1],[2]])
#make aumented matrix
part2_ex2=np.column_stack((N, b_part2))
part2_ex2=np.asfarray(part2_ex2,float)
part2_ex2

array([[ 2.,  3.,  3.,  1.],
       [ 3., -1.,  2., -1.],
       [ 1.,  4.,  2.,  2.]])

In [0]:
gauss(part2_ex2)

AssertionError: ignored

Now, we should get the same answer from part one

In [0]:
#gauss jordan


def gaussjordan(M):
  """
  create function to do jordan
  """
# make zero for storing augmented matrix
a = np.zeros((n,n+1))


x = np.zeros(n)

  for i in range(n):        
      for j in range(n):
          if i != j:
              ratio = a[j][i]/a[i][i]
              for k in range(n+1):
                  a[j][k] = a[j][k] - ratio * a[i][k]
 #have n't down yet

IndentationError: ignored

I did not get part 2 work correctly, 
but since it is chosen as answer from part1, for rref I should get an identity along with answer from part1.

## Part 3: Functions of matrices

Way 1: By proof

Let A matrix be be $$A_{n*k}$$, then $$A^T =A_{k*n}$$

$$A^T * A$$ will give a matrix of k by k 

On the right hand, $$A * A^T $$ will give a matrix of n by n.

In general, regardless of the the actual value of the matrix, as far as $$n \neq k $$ , the result of $$A * A^T \neq A^T *A $$ 
Simply example, (simply let n=2,k=3) we can easily see a 2by2 matrix does not equal to three by three matrix.

when n=k, it is also not hard to prove

Way 2: set up a system when n=k (for a squared matrix)

For simple calculation, I choose 2 by 2 matrix.

Let   $$A = \left[ \begin{array}{rrr}  a & b \\
                     c &d     \end{array}  \right]$$
                     then
                     
 $$A^T = \left[ \begin{array}{rrr}  a & c \\
                     b &d     \end{array}  \right]$$

In [0]:
#for special symbol
A = np.array([[abc.a,abc.b],[abc.c,abc.d]])
#left side
A_left= np.dot(A,A.T)
#right side
A_right=np.dot(A.T,A)
print("left side is",A_left)
print("right side is",A_right)

left side is [[a**2 + b**2 a*c + b*d]
 [a*c + b*d c**2 + d**2]]
right side is [[a**2 + c**2 a*b + c*d]
 [a*b + c*d b**2 + d**2]]


After clearing up the terms, we can see that only when $$a*c+b*d c^2 = a*b +c*d b^2$$

Therefore, in general, this can not hold true. 

### Under what conditions could this be true?

As it mentioned identity matrix will definitely work. technically when b=c, every matrix will also work for this 2 by 2 matrix. Then matrix should have the pattern as follows

$$A = \left[ \begin{array}{rrr}  a & b \\
                     b &d     \end{array}  \right]$$

## Part 4: Matrix factorization

Now, we can do LU factorization

In [0]:
#This method do not need to change data type
def my_LUdec(B):
    """
    Returns the string and slove using elimination
    """
    A = np.array(B)
    n = len(A)
    #print(A)
    
    #firstly make L,U all in zero,it follows the pattern and it can also make operation faster
    L = np.zeros(shape=(n,n))
    U = np.zeros(shape=(n,n))
    
 #Based on expanded form to create function 
    for k in range(n-1):
        gauss_vector = A[:,k]
        gauss_vector[k+1:] = gauss_vector[k+1:] / gauss_vector[k]
        gauss_vector[0:k+1] = np.zeros(k+1)
        L[:,k] = gauss_vector
        L[k][k] = 1.0
        #print(L)
        #print(A)
        for l in range(k+1,n):
            B[l,:] = B[l,:] - gauss_vector[l] * B[k,:]
            
        A = np.array(B)
    L[k+1][k+1] = 1.0
    U = A
    print("U is : \n",U)
    print("L is : \n",L)


 


In [294]:
# test example
M = np.array([[2,6,2],[5,9,0],[1,4,2]])

my_LUdec(M)
        

U is : 
 [[ 2  6  2]
 [ 1 -3 -4]
 [ 2  1 -2]]
L is : 
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [ 0. -1.  1.]]


Test ansswer with built-in function

In [295]:
#built in function

P, L, U = la.lu(M)


print(np.dot(L, U))

print("L is \n",L)
print("U is \n",U)

[[ 2.  6.  2.]
 [ 1. -3. -4.]
 [ 2.  1. -2.]]
L is 
 [[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [1.         0.83333333 1.        ]]
U is 
 [[ 2.          6.          2.        ]
 [ 0.         -6.         -5.        ]
 [ 0.          0.          0.16666667]]


## Part 5: Build your own function to solve a determinant for any matrix

Now, it is the time to build determinant function.

In [0]:
# Defines a function to compute matrix

def mydetfunc(matrix, mul): 
  """
  Returns the string of determinant of matrix based on given matrix and mul
  """
  #determine row and column of matrix
  width = len(matrix)
  #for only one matrix, answer is easy
  if width == 1:
    return mul * matrix[0][0]
  else:
    sign = -1
    sum = 0
    for i in range(width):
        m = []
        for j in range(1, width):
            buff = []
            for k in range(width):
                if k != i:
                    buff.append(matrix[j][k])
            m.append(buff)
        #change the sign of term,basically a big determinant can be treated as sum of smaller ones.
        #one importance is to decide right sign
        sign *= -1
        sum += mul * mydetfunc(m, sign * matrix[0][i])
    return sum
#test matrix
test_matrix = np.array([[2,8,-5],[3,-6,4],[1,2,-1]])


mydetfunc(test_matrix, 1)

-8

Then we start to test case.

For testing purpose, the setup testing matrix are showed as follows:



  $$A = \left[ \begin{array}{rrr}  4  &  5  \\
                     -2 &  7  \\
       \end{array}  \right]$$

   $$B = \left[ \begin{array}{rrr}  2 &  8 & -5  \\
                   3 & -6 &  4  \\
                   1 &  2 & -1  \end{array}  \right]$$
    $$C = \left[ \begin{array}{rrr}  2 &  8 & -5 &6 \\
                   3 & -6 &  4 &6 \\
                   8 & 3 &  4 &1\\
                   1 &  2 & -1 &2 \end{array}  \right]$$
                                  

In [296]:
#test for A
A = np.array([[4,-5],[-2,7]])
print("A:\n",A)

#test for B
B = np.array([[2,8,-5],[3,-6,4],[1,2,-1]])
print("B:\n",B)

#test for C
C = np.array([[2,8,-5,6],[3,-6,4,6],[8,3,4,1],[1,2,-1,2]])
print("C:\n",C)



A:
 [[ 4 -5]
 [-2  7]]
B:
 [[ 2  8 -5]
 [ 3 -6  4]
 [ 1  2 -1]]
C:
 [[ 2  8 -5  6]
 [ 3 -6  4  6]
 [ 8  3  4  1]
 [ 1  2 -1  2]]


In [297]:
#start with own function


det_A=mydetfunc(A,1)
print("detA:\n",det_A_builtin)

det_B=mydetfunc(B,1)
print("detB:\n",det_B_builtin)


det_C= mydetfunc(C,1)
print("detC:\n",det_C_builtin)

detA:
 17.999999999999996
detB:
 -7.999999999999995
detC:
 -13.999999999999984


Test ansswer with built-in function

In [298]:
# answer with built in function
det_A_builtin= np.linalg.det(A)
print("built in detA:\n",det_A_builtin)

det_B_builtin= np.linalg.det(B)
print("built in detB:\n",det_B_builtin)



det_C_builtin= np.linalg.det(C)
print("built in detC:\n",det_C_builtin)

built in detA:
 17.999999999999996
built in detB:
 -7.999999999999995
built in detC:
 -13.999999999999984


By comparing built in function and own function result, I am safe to say it satisfy the requirement.

## Part 6: Build your own function from scratch to solve equations via Cramer’s rules.

To make case easier, I still use the matrix A,B and C frrom part five. also I need to introduce a,b,c 

In [0]:
#we have previous matrix A,B and C which are 2by2, 3by3 and 4by4, now I am adding b term
a = np.array([[3],[5]])
b = np.array([[2],[3],[1]])
c = np.array([[7],[3],[1],[-1]])

Based on Text book, 

To make a generalized function, firstly test wwith 4 by 4 matrix. Also, for easier computation, I use the same matrix from part 5.

In [0]:
#hard code
# make a 3 by 3 matrix 

In [299]:
#using case for 4 by 4 matrix
A=np.array([[2,8,-5,6],[3,-6,4,6],[8,3,4,1],[1,2,-1,2]])
b=np.array([[7],[3],[1],[-1]])
C=np.array([[2,8,-5,6],[3,-6,4,6],[8,3,4,1],[1,2,-1,2]])
X=[]
for i in range(0,len(b)):
    for j in range(0,len(b)):
        C[j][i]=b[j]
        if i>0:
            C[j][i-1]=A[j][i-1]
    X.append(round(np.linalg.det(C)/np.linalg.det(A),1))
 
print('x_1=%s'%X[0],'x_2=%s'%X[1],'x_3=%s'%X[2],'x_4=%s'%X[3])

x_1=110.4 x_2=-85.5 x_3=-145.7 x_4=-43.1


Check with Matlab, the answer is true.

Then I tried to make it generalized case

Actual code for general rule. I will use matrix inverse for it. 

In [0]:
def func_cramer(m,b):
#set up with blank term
    m_i = []
    for i in range(b.shape[0]):
        m_i.append(copy.deepcopy(m))
        #fix line issue
        m_i[i][:,i] =b
        pass
    x = []
    for i in range(b.shape[0]):
      #this is old det, since during the time my determinant does not
        x.append(np.linalg.det(m_i[i]) / np.linalg.det(m))
    print(x)


In [301]:
m = np.array([[2,8,-5,6],[3,-6,4,6],[8,3,4,1],[1,2,-1,2]])
b = np.array([7,3,1,-1])
func_cramer(m,b)


[110.4285714285715, -85.50000000000014, -145.71428571428586, -43.0714285714286]


For some reason, b does not work properly, (transpose not work on this array type)

But we get the same answer. We can try other matrice.

In [302]:
m = np.array([[2,8,-5],[3,-6,4],[1,2,-1]])
#retype the array
b = np.array([2,3,1])
func_cramer(m,b)

[1.0, -0.0, -0.0]


In [303]:
m = np.array([[4,-5],[-2,7]])
b= np.array([3,5])
func_cramer(m,b)

[2.5555555555555562, 1.4444444444444442]


Since all three answer work, I assumed this is function for general Cramer's rule.

Check with matlab, answers also fits the general rule

## Reference##
For part 2:

Matlab back sustitution 
http://cis.poly.edu/~mleung/CS3734/s03/ch02/backSubstitutionU.htm

Matlab 
https://www.youtube.com/watch?v=juDxSMpzv6c

Gauss-Jordan Elimination
https://online.stat.psu.edu/statprogram/reviews/matrix-algebra/gauss-jordan-elimination

code by C
https://www.geeksforgeeks.org/gaussian-elimination/


Part4: 


https://elonen.iki.fi/code/misc-notes/python-gaussj/

